version: "3.7"
services:
  mysql:
    container_name: "some_name"
    image: "mysql/mysql-server:5.6"
    command:
      - mysqld
      - "--init-connect='SET NAMES utf8'"
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql:rw,noexec,nosuid,size=1024m
    volumes:
      - "some_path:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=host
      - TZ=Asia/Bangkok
